### ISSUE TITLE
Error while executing the "go build" command

### ISSUE THREAD

**Issue by sbcd90** [wangkuiyi/go-cpp#1]
Hello,

I'm getting the following error when executing "go build cgo_lib.go" -

command-line-arguments

C:\Users\i076326\AppData\Local\Temp\go-build956025423\command-line-arguments_obj\cgo_lib.cgo2.o: In function '_cgo_1ee745840363_Cfunc_CRandom':

C:/Users/i076326/Documents/programs/go-cpp/go/src/cgo_lib/cgo_lib.go:35: undefined reference to 'CRandom'
collect2.exe: error: ld returned 1 exit status

can you kindly help me in resolving this issue?

any help on this is appreciated. hoping to get a reply from you soon.

**Comment by wangkuiyi** [comment]
Please see this change: https://github.com/wangkuiyi/go-cpp/pull/2

I think the error is due to the #cgo directive I used in cgo_lib.go.  I removed the constraints of drawin in above change.

You can try clone above pull request using git clone -b nodarwin https://github.com/wangkuiyi/go-cpp, and try again.

**Comment by sbcd90** [comment]
Thanks..this works...
